### ISSUE TITLE
REST - Problem z metodą PUT na zewnętrznym VPSie

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#116]
Postawiłem na swoim VPSie sealiousa z npm'a z moją aplikacją. Metoda POST jest akceptowana. Próba aktualizacji zasobu przez metodę PUT kończy się błędem 500. Testowane w aplikacji klienckiej oraz przez postmana (oczywiście po zalogowaniu)
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}
```
Log z serwera
```bash
Debug: internal, implementation, error 
    TypeError: Uncaught error: undefined is not a function
    at www_server.route.handler (/usr/local/lib/node_modules/sealious/node_modules/sealious-base-chips/define/channel.rest.js:100:26)
    at arguments.(anonymous function).handler (/usr/local/lib/node_modules/sealious/node_modules/sealious-base-chips/define/channel.www_server.js:92:17)
    at Object.internals.handler (/usr/local/lib/node_modules/sealious/node_modules/hapi/lib/handler.js:94:36)
    at /usr/local/lib/node_modules/sealious/node_modules/hapi/lib/handler.js:28:23
    at internals.Protect.run (/usr/local/lib/node_modules/sealious/node_modules/hapi/lib/protect.js:56:5)
    at exports.execute (/usr/local/lib/node_modules/sealious/node_modules/hapi/lib/handler.js:22:22)
    at /usr/local/lib/node_modules/sealious/node_modules/hapi/lib/request.js:331:13
    at iterate (/usr/local/lib/node_modules/sealious/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/usr/local/lib/node_modules/sealious/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /usr/local/lib/node_modules/sealious/node_modules/hapi/node_modules/hoek/lib/index.js:796:22
    at process._tickDomainCallback (node.js:381:11)

```

**Comment by debian-sh** [comment]
Ok kwestia wrzucenia fix'a na npm'a

**Comment by groovy354** [comment]
Wrzuciłem najnowszą wersję na NPM. Zaktualizuj sealiousa u siebie na vpsie i jeżeli ten błąd już nie występuje, zamknij issue :)

**Comment by debian-sh** [comment]
Problem cały czas występuje

**Comment by debian-sh** [comment]
Ok naprawione :+1:
