### ISSUE TITLE
[sealious-base-chips][use/channel.www_server.js] Czerwony stos

### ISSUE THREAD

**Issue by theadimar21** [Sealious/Sealious#124]
Przy ```PUT /api/v1/users/me``` następuje zawiecha klienta RESTowego (np. Postmana na Chromie, czy REST Easy na Firefoksie), a Sealious wypluwa czerwony stos.

Link do issue na sealious-base-chips: https://github.com/Sealious/sealious-base-chips/issues/1

**Comment by debian-sh** [comment]
Wrzuć output z konsoli :)

**Comment by theadimar21** [comment]
```
Unhandled rejection TypeError: Cannot read property 'userdata_id' of undefined
    at /home/adrian/Documents/sealious-base-chips/define/service.user_manager.js:69:34
    at tryCatcher (/home/adrian/Documents/sealious-base-chips/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/adrian/Documents/sealious-base-chips/node_modules/bluebird/js/main/promise.js:466:31)
    at Promise._settlePromiseAt (/home/adrian/Documents/sealious-base-chips/node_modules/bluebird/js/main/promise.js:545:18)
    at Promise._settlePromises (/home/adrian/Documents/sealious-base-chips/node_modules/bluebird/js/main/promise.js:661:14)
    at Async._drainQueue (/home/adrian/Documents/sealious-base-chips/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/home/adrian/Documents/sealious-base-chips/node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/adrian/Documents/sealious-base-chips/node_modules/bluebird/js/main/async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Prosz

**Comment by theadimar21** [comment]
Zamknięte, 27a65f0e7e9
