### ISSUE TITLE
Field-type should not need to be a constructor

### ISSUE THREAD

**Issue by groovy354** [Sealious/Sealious#206]

**Comment by debian-sh** [comment]
I will change old field-types. :)

**Comment by debian-sh** [comment]
Ok, I changed it. At now we have problem with constructor of Field-type in `resource-type-field.js`.


```js
/home/arkadiusz/Projects/Sealious-development/Sealious/lib/chip-types/resource-type-field.js:21
    this.type = new type_constructor();
                ^
TypeError: object is not a function
    at ResourceTypeField (/home/arkadiusz/Projects/Sealious-development/Sealious/lib/chip-types/resource-type-field.js:21:17)
    at add_field (/home/arkadiusz/Projects/Sealious-development/Sealious/lib/chip-types/resource-type.js:36:22)
    at add_fields (/home/arkadiusz/Projects/Sealious-development/Sealious/lib/chip-types/resource-type.js:47:9)
    at _process_declaration (/home/arkadiusz/Projects/Sealious-development/Sealious/lib/chip-types/resource-type.js:29:10)
    at ResourceType (/home/arkadiusz/Projects/Sealious-development/Sealious/lib/chip-types/resource-type.js:21:7)
    at Object.<anonymous> (/home/arkadiusz/Projects/Sealious-development/Sealious/lib/base-chips/resource_type.user.js:2:12)
```
