### ISSUE TITLE
Problem with creating new user under sealious-datastore-tingo

### ISSUE THREAD

**Issue by debian-sh** [Sealious/Sealious#227]
In `sealious-datastore-mongo` `user-manager` works fine, but when I try to create new user with `sealious-datastore-tingo` in Postman, I got this red stack.

```js
20:35:07.269 - info: Sealious@0.6.3 is up-to-date.
Unhandled rejection SyntaxError: Unexpected number
    at tcoll.__find (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/tcoll.js:1043:83)
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/tcoll.js:1086:8
    at wqueue._exec (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/wqueue.js:36:3)
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/wqueue.js:32:9
    at Object.async.eachSeries (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/async/lib/async.js:142:20)
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/tcoll.js:137:11
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/safe/lib/safe.js:233:13
    at _catcher (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/safe/lib/safe.js:250:4)
    at _run (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/safe/lib/safe.js:278:3)
    at Object.safe.run (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/safe/lib/safe.js:1023:3)
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/tcoll.js:127:9
    at _catcher (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/safe/lib/safe.js:245:14)
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/safe/lib/safe.js:331:4
    at Object.async.whilst (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/async/lib/async.js:683:13)
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/node_modules/async/lib/async.js:679:23
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/tcoll.js:122:12
```
Postman returns nothing.

Second try returns
```js
Debug: internal, implementation, error 
    SyntaxError: Uncaught error: Unexpected number
    at tcoll.__find (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/tcoll.js:1043:83)
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/tcoll.js:1086:8
    at wqueue._exec (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/wqueue.js:36:3)
    at /home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/node_modules/sealious-datastore-tingo/node_modules/tingodb/lib/wqueue.js:54:10
    at doNTCallback0 (node.js:407:9)
    at process._tickDomainCallback (node.js:377:13)
```
Postman returns 500.

**Comment by debian-sh** [comment]
@groovy354 Do you want make pull request to https://github.com/Sealious/tingodb?

**Comment by groovy354** [comment]
We'll see. I've forked the repo and realized we're using an outdated version of Tingo. I'll update our dependencies and see if the problem persists

**Comment by groovy354** [comment]
I've updated the dependencies. I've tested it on my machine and it worked. Please install the newest version of Sealious and confirm that the issue has been resolved.

**Comment by debian-sh** [comment]
Ok, in a moment I'll install

**Comment by debian-sh** [comment]
I have noticed other issue, we can create new user with the same username indefinitely. (tingo & mongo)

```js
15:18:31.388 - info: User pi has been created
15:18:31.404 - info: 	POST /api/v1/users
			from: 127.0.0.1, mime: multipart/form-data
			result: success!
15:18:32.032 - info: User pi has been created
15:18:32.035 - info: 	POST /api/v1/users
			from: 127.0.0.1, mime: multipart/form-data
			result: success!
15:18:32.533 - info: User pi has been created
15:18:32.537 - info: 	POST /api/v1/users
			from: 127.0.0.1, mime: multipart/form-data
			result: success!
15:18:32.961 - info: User pi has been created
15:18:32.969 - info: 	POST /api/v1/users
			from: 127.0.0.1, mime: multipart/form-data
			result: success!
```

**Comment by groovy354** [comment]
If that is the case, it's another issue, so please file it as a separate one.
Is the issue with field-types resolved for you?

**Comment by debian-sh** [comment]
No, issue with field-types is not resolved for me.

**Comment by groovy354** [comment]
Is the issue with tingodb errors resolved for you?

**Comment by debian-sh** [comment]
Ok, this issue is resolved.
